# Generated by Django 3.1.5 on 2021-01-14 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_slider'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slider',
            new_name='HeadSlider',
        ),
    ]
